stages:
  - check
  - build
  - deploy

default:
  image: ubuntu
  before_script:
    - apt update
    - apt install -y make ca-cacert emacs

check:
  script:
    - make check
  stage: check

build:
  script:
    - make
  stage: build
